---
engines:
  duplication:
    enabled: false
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
ratings:
  paths:
  - src/**
exclude_paths:
- test/
- lib/
- node_modules/