language: node_js
node_js:
- '8'
notifications:
  email: false
deploy:
  provider: npm
  email: davidstoreypickart@gmail.com
  api_key:
    secure: ZDCaDxXGRs7w6KJSyIB1oInEYY4GDClkb6FY+Zf4aZdnquFL6OHm8cwQK//aUfYtdOzfNgCHyN8wIM842k7wtxS1f95iCLrS/74Hifdfae43hgGnp8/ZyeomcLTbK8rZj12KndYH+sz1Gm3tW5W1SS+d8iMVl6VOm4nxO5XbrRNQcdcNpHee5FigJcjf8O1MOelhVqoeuKYte5cwgoMdD9qu/t/sGGUb+WzPvzOomFgvWyeX8c+eXMubrnfQve/8hMb10/TbQS8dySpPbzeV+z/3vF4LKPF2sxHPKbvIbHLujtU0GhQP1S5Jc93ER3AVOZuR+iWRMgzwFFDbyBq+Ybndfz4iErFjNRzFoKOTTl3vzZYs2hHaT3xAVIHVOfsmP2oegfJDJdCd1SGXEk19VpghtRY28Sb6oxTHkATAgVmF0L5cOYK7aNkQtyjA9YX929MsCrf1ahqp5SSJ7hL7ou+yOafpAqFDRPIQbWQKITs9KVk8h+twOqIUNHWIAwR4QrQ0OHqpfppyNuRTJeCUR4JgpYQdBncfX3ZE001a6CySWUisDrVKeBlVyPQP8TSQOiKR2Bw290QKnAvcLf2Lqb2MAanfA6k26k6zo+ZJOauDz01GS3XNcY0d9m145O7MVV835pw9m6HfB43RFyey7S8roRiQNB8SUtJl+F/TXeA=
  on:
    branch: master
  skip_cleanup: true
