import React from 'react'
import PropTypes from 'prop-types'
import { flashMessageType } from 'redux-flash'
import classnames from 'classnames'

/**
 *
 * A component that displays a flash message generated by [redux-flash](https://github.com/LaunchPadLab/redux-flash).
 * Any message props will be passed through to this component.
 * 
 * @name FlashMessage
 * @type Function
 * @param {Object} message - The flash message that will be displayed.
 * @param {Function} [onDismiss] - A callback for dismissing the flash message. The dismiss button will only be shown if this callback is provided.
 * @example
 * 
 * function ManyMessages ({ messages }) {
 *   return (
 *      <div>
 *         {
 *            messages.map(message => <FlashMessage key={ message.id } message={ message } />)
 *         }
 *      </div>
 *   )
 * }
 *
 */

const propTypes = {
  message: flashMessageType.isRequired,
  onDismiss: PropTypes.func,
}

const defaultProps = {
  onDismiss: null,
}

function FlashMessage ({ message, onDismiss }) {
  const statusClass = message.isError ? 'failure' : 'success'
  return (
    <div { ...message.props } className={ classnames('flash-message', statusClass, message.props.className) }>
      { 
        onDismiss &&
        <button type="button" className="dismiss" onClick={ () => onDismiss(message) }>
          X
        </button>
      }
      <p> { message.message } </p>
    </div>
  )
}

FlashMessage.propTypes = propTypes
FlashMessage.defaultProps = defaultProps

export default FlashMessage
