import React from 'react'
// import PropTypes from 'prop-types'
import { flashMessageType } from 'redux-flash'
import classnames from 'classnames'

/**
 *
 * A component that displays a flash message generated by [redux-flash](https://github.com/LaunchPadLab/redux-flash).
 * 
 * @name FlashMessage
 * @type Function
 * @param {Object} message - The flash message that will be displayed.
 * @example
 * 
 * function ManyMessages ({ messages }) {
 *   return (
 *      <div>
 *         {
 *            messages.map(message => <FlashMessage key={ message.id } message={ message } />)
 *         }
 *      </div>
 *   )
 * }
 *
 */

const propTypes = {
  message: flashMessageType.isRequired,
}

const defaultProps = {}

function FlashMessage ({ message: { message, isError } }) {
  const statusClass = isError ? 'failure' : 'success'
  return (
    <div className={ classnames('flash-message', statusClass) }>
      <p> { message } </p>
    </div>
  )
}

FlashMessage.propTypes = propTypes
FlashMessage.defaultProps = defaultProps

export default FlashMessage
